plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml
  - .rubocop/layout.yml
  - .rubocop/metrics.yml
  - .rubocop/rspec.yml
  - .rubocop/style.yml

AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.0
