plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest

inherit_from:
  - .rubocop_todo.yml
  - .rubocop/layout.yml
  - .rubocop/metrics.yml
  - .rubocop/minitest.yml
  - .rubocop/style.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.0
