inherit_from:
  - .rubocop_todo.yml
  - .rubocop/layout.yml
  - .rubocop/metrics.yml
  - .rubocop/style.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  SuggestExtensions: true
  TargetRubyVersion: 2.6
