name: Push gem to RubyGems

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  push:
    if: github.repository == 'httprb/http'
    runs-on: ubuntu-latest

    environment:
      name: rubygems.org
      url: https://rubygems.org/gems/http

    permissions:
      contents: write
      id-token: write

    strategy:
      matrix:
        ruby: [ ruby, jruby ]

    steps:
      - uses: actions/checkout@v6

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: rubygems/release-gem@v1
        env:
          HTTP_PLATFORM: ${{ matrix.ruby == 'jruby' && 'java' || '' }}

      - name: Create GitHub release
        run: |
          tag_name="$(git describe --tags --abbrev=0)"
          gh release create "${tag_name}" --verify-tag --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.ruby == 'ruby'
